# Generated by Django 2.1.2 on 2018-10-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorSurveyForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('articleid', models.IntegerField(blank=True, null=True)),
                ('publishyear', models.IntegerField(blank=True, null=True)),
                ('datasetname', models.CharField(blank=True, max_length=255, null=True)),
                ('refid', models.IntegerField(blank=True, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('authorid', models.IntegerField(blank=True, null=True)),
                ('authorname', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'author_survey_form',
                'managed': False,
            },
        ),
    ]
